server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /poi {
        return 301 /poi/;
    }

    location ^~ /poi/ {
        try_files $uri $uri/ =404;
    }

    location / {
        return 404;
    }
}